### PR TITLE
Array Insertion through C++

### PR DESCRIPTION
**Pull request by mananaggarwal2001**

### CODE REVIEW

**Comment by harish127** [comment]
hey can you give more description?

**Comment by mananaggarwal2001** [comment]
Sir this is Genuine Pull request as this pull request is not the thread and you can also check this pull request as it contain the code of the Linked List Insertion and you can run this request also

**Comment by mananaggarwal2001** [comment]
Sir this is the valid pull request as it contain the code about the linked list insertion in which we can create the linked list and Modes of insertion is described in  this Linked list through the switch case like insertion from the beginning and more functions etc. Pls Approve this pull request   Sent from Mail for Windows From: Harish Kumar KaiwartSent: Sunday, October 3, 2021 1:11 PMTo: vishnudas-bluefox/HacktoberFest-2021Cc: AnonymousManan; AuthorSubject: Re: [vishnudas-bluefox/HacktoberFest-2021] Array Insertion through C++ (#19) hey can you give more description?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mananaggarwal2001** [comment]
And this pull request contain the  all the types and mode of the insertion in the linked list like beginning , ending , at a given particular position and so on...

**Pull request closed without merging**
